'string'.padStart(10);          // " string" 
'string'.padStart(10, "abc");   // "abcastring" 
'string'.padStart(10,"123465"); // "1234string"
'string'.padStart(8, "0");      // "00string"
'string'.padStart(3);           // "string"
'string'.padEnd(10);            // "string    "
'string'.padEnd(10, "abc");     // "stringabca"
'string'.padEnd(8, "123456");   // "string12"
'string'.padEnd(1);             // "string"
